### ISSUE TITLE
Bad install link

### ISSUE THREAD

**Issue by Pytlicek** [jprante/elasticsearch-index-termlist#12]
Bad install link in README.

Here is correct :)

./bin/plugin -install index-termlist -url http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-index-termlist/1.4.0.2/elasticsearch-index-termlist-1.4.0.2-plugin.zip

**Comment by rochacbruno** [comment]
:+1: same problem here

**Comment by jprante** [comment]
Thanks. Fixed now with forgot commit of 1.4.0.2
