### ISSUE TITLE
Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

### ISSUE THREAD

**Issue by boferri** [jprante/elasticsearch-index-termlist#28]
elasticsearch/bin/plugin install jprante/elasticsearch-index-termlist
-> Installing jprante/elasticsearch-index-termlist...
Trying https://github.com/jprante/elasticsearch-index-termlist/archive/master.zip ...
Downloading ............................................................................................................................................DONE
Verifying https://github.com/jprante/elasticsearch-index-termlist/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by jprante** [comment]
You have to use the URL

```
./bin/plugin -install index-termlist -url http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-index-termlist/...
```

Please see README https://github.com/jprante/elasticsearch-index-termlist/blob/master/README.md

**Comment by boferri** [comment]
@jprante this doesn't work with 2.4.1 (see https://www.elastic.co/guide/en/elasticsearch/plugins/2.4/installation.html)
anyway, I was able to locally compile and make the zip from https://github.com/jilen/elasticsearch-index-termlist, which I could install successfully ;)
